### ISSUE TITLE
Sesión 4 - Algunas puntualizaciones

### ISSUE THREAD

**Issue by fjaviermmdev** [GinesGarcia/computacion_movil_um#1]
Hola! He ido siguiendo toda la guía de la sesión 4 y todo funciona bien, pero me gustaría puntualizar un par de cosas:

- Hay un par de momentos en el código donde se buscan TextViews por su ID, concretamente en la siguiente línea: `TextView textView = findViewById(R.id.locationTV);`. Sin embargo, en el código no se indica que se tenga que crear un TextView con ese ID, el único que se indica es con el ID `secondActTV`. Creo que sería conveniente cambiarlo.
- En cuanto a la solicitud activa de la ubicación, concretamente en el código donde se indica la solicitud de suscripción al servicio de actualización (clase LocationRequest), hay dos posibles imports: hay que elegir `import com.google.android.gms.location.LocationRequest;` en vez del otro import. Los métodos en cuestión salen deprecated, pero son los correctos. Con el otro import saldrían fallos.

**Comment by GinesGarcia** [comment]
Hola @xJavii8 , muchas gracias por tus comentarios!!! 
Intento aclararlo en la siguiente version.

Gracias!!
