### ISSUE TITLE
Sesión 5 - Puntualizaciones

### ISSUE THREAD

**Issue by fjaviermmdev** [GinesGarcia/computacion_movil_um#2]
Hola! Al igual que con la sesión 4, he ido siguiendo la guía de la sesión 5 y todo funciona, pero puntualizar algunas cosas:

- A la hora de crear la segunda actividad, donde se debe de crear el `TextView `de `Telephony Activity` y demás debería de ser en el archivo `activity_telephony.xml`, no en `activity_location.xml`. 
- En la función `showCellInfo`, `text `no está definido. Como tiene varios `appends`, imagino que este debería de ser un objeto `StringBuilder`. Finalmente también se debería de añadir a un `TextView`, aunque eso tampoco está comentado.

**Comment by GinesGarcia** [comment]
Hola,
muchas gracias!! he incluido las correcciones :)

Un saludo,
Ginés.

**Comment by GinesGarcia** [comment]
Closing
